# Generated by Django 2.2.10 on 2020-05-02 01:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_height', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5.0)])),
                ('font_size', models.IntegerField(default=14)),
                ('char_width', models.IntegerField(default=80)),
                ('color', models.CharField(default='000000', max_length=6, validators=[documents.models.validate_rgb_hex])),
                ('font_family', models.CharField(choices=[('Georgia', 'Georgia'), ('serif', 'serif'), ('Times New Roman', 'Times New Roman'), ('Arial', 'Arial'), ('Helvetica', 'Helvetica'), ('sans-serif', 'sans-serif'), ('Tahoma', 'Tahoma')], default='Georgia', max_length=24)),
                ('num_chars', models.IntegerField(default=0)),
                ('contents', models.TextField(blank=True)),
                ('title', models.TextField(default='My new document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
