# Generated by Django 3.0.4 on 2020-04-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.TextField(default='My new document'),
        ),
    ]
