# Generated by Django 3.0.4 on 2020-04-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='font_family',
            field=models.CharField(choices=[('georgia', 'georgia'), ('serif', 'serif'), ('times_new_roman', 'times_new_roman'), ('arial', 'arial'), ('sans_serif', 'sans_serif'), ('tahoma', 'tahoma')], default='georgia', max_length=24),
        ),
    ]
