# Generated by Django 2.2.10 on 2020-05-03 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='documents.Document'),
        ),
    ]
