# Generated by Django 2.2.10 on 2020-05-03 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20200503_0511'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='highlight',
            unique_together=set(),
        ),
    ]
