# Generated by Django 3.0.4 on 2020-04-23 03:16

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20200423_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='color',
            field=models.CharField(default='000000', max_length=6, validators=[documents.models.validate_rgb_hex]),
        ),
    ]
