# Generated by Django 3.0.4 on 2020-04-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='char_width',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='document',
            name='font_size',
            field=models.IntegerField(default=14),
        ),
    ]
