# Generated by Django 3.0.4 on 2020-04-23 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20200423_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_deleted',
        ),
    ]
