# Generated by Django 3.0.4 on 2020-04-24 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_line_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='line_height',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
