# Generated by Django 3.0.4 on 2020-04-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20200424_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='font_family',
            field=models.CharField(choices=[('Georgia', 'Georgia'), ('serif', 'serif'), ('Times New Roman', 'Times New Roman'), ('Arial', 'Arial'), ('Helvetica', 'Helvetica'), ('sans-serif', 'sans-serif'), ('Tahoma', 'Tahoma')], default='Georgia', max_length=24),
        ),
    ]
